### ISSUE TITLE
Add instructions on how to handle bug on step #33 of 05installCP4BA.md

### ISSUE THREAD

**Issue by jorgedr94** [IBM/cp4ba-rapid-deployment#2]
Currently there is a bug on the CP4BA when trying to add a user group with a single role.   Basically if you try to add a user group as stated on step #33 you will get the following error message. 

![image](https://user-images.githubusercontent.com/25494074/135350205-2e523693-0415-4a1c-98cc-df9880ae79e9.png)

We have to update the instructions to tell users the work around this issue.  The work around is to select more than one role when adding the group then click the Create button.

**Comment by tschulze1890** [comment]
@jorgedr94 Step 33 atm says: "On the Roles page select role Automation Developer and User, then click Next", so two roles.

What is missing?

**Comment by tschulze1890** [comment]
Closing...
